#!/usr/bin/env bash
# Installs nginx server
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html
service nginx start
