#!/usr/bin/env bash
#configure a 404 page

sudo apt-get update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
chmod -R 755 /var/www
echo 'Hello World' > /var/www/html/index.html
host_name=$(hostname)

my_config=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;
               root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        location / {
                add_header X-Served-By $host_name;
                try_files \$uri \$uri/ =404;
        }
        error_page 404 /404.html;
        location  /404.html {
            internal;
        }
        
        if (\$request_filename ~ redirect_me){
            rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
        }
}
"
echo "Ceci n'est pas une page" > /var/www/html/404.html
echo "$my_config" > /etc/nginx/sites-available/default

if [ "$(pgrep -c nginx)" -le 0 ];
then
    service nginx start
else
    service nginx restart
fi;
