#!/usr/bin/env bash
#prints Best School ten times(to be reviewed later)
i=0
while((i < 10));
do
	if((i==3));
	then
		echo "bad luck"
	elif((i==7));
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
