#!/usr/bin/env bash
#prints from 1 to 20(to be reviewed later)
count=1
while((count <= 20));
do
	echo "$count"
	case $count in
	"4") echo "bad luck from China";;
	"9") echo "bad luck from Japan";;
	"17") echo "bad luck from Italy";;
	esac
	((count++))
done
