#!/usr/bin/env bash
#Bash script that displays all active IPv4 IPs on the machine
#it’s executed on.
interfaces=$(ifconfig | awk -F ' ' '{print $1}' | grep -E '^[a-z]+[0-9]+')

# Loop through each interface and extract the IPv4 address
for interface in $interfaces; do
  # Get the IPv4 address for the current interface
  ip=$(ifconfig "$interface" | awk '/inet / {print $2}')
  # Print the IPv4 address
  echo "$ip"
done

